version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres
    # automatically restarts the container - Docker daemon on restart or
    # the container itself is manually restarted
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - /root/docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    # automatically restarts the container - Docker daemon on restart or
    # the container itself is manually restarted
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "marcos.antonio.carvalho@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "master"
    ports:
      - "54321:80"
    volumes:
      - /root/docker/volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
